### ISSUE TITLE
What does "A+, ?" for the TLS means?

### ISSUE THREAD

**Issue by unixfox** [dalf/searx-stats2#37]
![image](https://user-images.githubusercontent.com/4016501/85149817-45176180-b241-11ea-8160-3e6ba313d68e.png)

What is the question mark supposed to be?

**Comment by dalf** [comment]
The result from the different IP are merged when they are identical. It is not the case here.

```sh
docker run -ti --name=cryptcheck-backend --rm -e BUG_METHOD_UNSUPPORTED_TIMEOUT=1 -e SLOW_DOWN=0.1 dalf/cryptcheck-backend:latest
curl http://127.0.0.1:7000/https/searx.be.json
```

It returns 
* A+ for your searx.be IPv4.
* ```"error": "TLS seems not supported on this server"``` for your searx.be IPv6.

This is wrong: 
* curl doesn't see any issue using the IPv6.
* cryptcheck.fr returns A+ for both IP.

So I guess this is a [cryptcheck-backend](https://github.com/dalf/cryptcheck-backend) bug.

**Comment by dalf** [comment]
```
root@al-f:/srv/cryptcheck-backend# docker run --rm --network host -e BUG_METHOD_UNSUPPORTED_TIMEOUT=1 -e SLOW_DOWN=1 aeris22/cryptcheck https searx.be
/cryptcheck/lib/cryptcheck/tls/engine.rb:338:in `rescue in connect': Timeout when connecting to 2a00:6d40:60:b060::1:443 (max 10 seconds) (CryptCheck::Tls::Engine::Timeout)
	from /cryptcheck/lib/cryptcheck/tls/engine.rb:344:in `connect'
	from /cryptcheck/lib/cryptcheck/tls/engine.rb:415:in `ssl_client'
	from /cryptcheck/lib/cryptcheck/tls/engine.rb:68:in `supported_method?'
	from /cryptcheck/lib/cryptcheck/tls/engine.rb:79:in `block in fetch_supported_methods'
```

```
curl -v -6 -o /dev/null https://searx.be/

...
*   Trying 2a00:6d40:60:b060::1...
* TCP_NODELAY set
* Expire in 200 ms for 4 (transfer 0x55977ccdee80)
* Connected to searx.be (2a00:6d40:60:b060::1) port 443 (#0)
...

```
